### ISSUE TITLE
[BUG] Installation command error and gromacs version issue

### ISSUE THREAD

**Issue by TsuKuanLin** [shunsakuraba/fepsuite#2]
Dear Prof.Sakuraba, Thanks for the very detail installation guideline! 

But while installing, I found out that a command in fepsuite/feprest/README has wrong:
line 57: `g++ --ffast-math -O3 -o FASPR src/*.cpp`
It should be `g++ -ffast-math -O3 -o FASPR src/*.cpp`

Also I've try before installing Gromacs 2020, 2020.2, and failed in the command
`patch -p1 < /path/to/fepsuite/feprest/gmx_patch/gromacs-2020-hrex.patch` and remaining command.
According to the file in gmx_patch, maybe it is better to specfiy the gromacs version should be 2020.7? Installing gromacs 2020.7 is totally works find to me. 

Thanks for the beautiful code for the project!

**Comment by shunsakuraba** [comment]
Thank you for the feedback! Fixed in commit b5f266e.
